
//1
// let elements= document.querySelectorAll('.redBg')
// elements.style.backgroundColor = "red"
// //2
// let element= document.querySelector('.clickMe')
// element.addEventListener("click", ()=>{
// alert( 'Your screen resolution is ' + screen.width + 'x' + screen.height );
// });
//3
let x = 10

// if (x<==011){
//     return console.log('true')
// }

if (x>=Math.E){
     console.log('true')
}

if (x===O*0 A){
     console.log('true 2')
}
if(x==='10'){
      console.log('true 3')
}

if(x<0x10){
return console.log('true 4')
}